# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input sensor drivers
#

# Hall sensors
obj-$(CONFIG_HS_MH248_FYDE)		+= hall/

# Fingerprint sensors
obj-y                         += fingerprint/
